INSERT INTO HERO (name, localized_name, primary_attribute) VALUES
 ('antimage','Anti-Mage','AGI')
,('axe','Axe','STR')
,('bane','Bane','INT')
,('bloodseeker','Bloodseeker','AGI')
,('crystal_maiden','Crystal Maiden','INT')
,('drow_ranger','Drow Ranger','AGI')
,('earthshaker','Earthshaker','STR')
,('juggernaut','Juggernaut','AGI')
,('mirana','Mirana','AGI')
,('nevermore','Shadow Fiend','AGI')
,('morphling','Morphling','AGI')
,('phantom_lancer','Phantom Lancer','AGI')
,('puck','Puck','INT')
,('pudge','Pudge','STR')
,('razor','Razor','AGI')
,('sand_king','Sand King','STR')
,('storm_spirit','Storm Spirit','INT')
,('sven','Sven','STR')
,('tiny','Tiny','STR')
,('vengefulspirit','Vengeful Spirit','AGI')
,('windrunner','Windranger','INT')
,('zuus','Zeus','INT')
,('kunkka','Kunkka','STR')
,('lina','Lina','INT')
,('lich','Lich','INT')
,('lion','Lion','INT')
,('shadow_shaman','Shadow Shaman','INT')
,('slardar','Slardar','STR')
,('tidehunter','Tidehunter','STR')
,('witch_doctor','Witch Doctor','INT')
,('riki','Riki','AGI')
,('enigma','Enigma','INT')
,('tinker','Tinker','INT')
,('sniper','Sniper','AGI')
,('necrolyte','Necrophos','INT')
,('warlock','Warlock','INT')
,('beastmaster','Beastmaster','STR')
,('queenofpain','Queen of Pain','INT')
,('venomancer','Venomancer','AGI')
,('faceless_void','Faceless Void','AGI')
,('skeleton_king','Wraith King','STR')
,('death_prophet','Death Prophet','INT')
,('phantom_assassin','Phantom Assassin','AGI')
,('pugna','Pugna','INT')
,('templar_assassin','Templar Assassin','AGI')
,('viper','Viper','AGI')
,('luna','Luna','AGI')
,('dragon_knight','Dragon Knight','STR')
,('dazzle','Dazzle','INT')
,('rattletrap','Clockwerk','STR')
,('leshrac','Leshrac','INT')
,('furion','Nature''s Prophet','INT')
,('life_stealer','Lifestealer','STR')
,('dark_seer','Dark Seer','INT')
,('clinkz','Clinkz','AGI')
,('omniknight','Omniknight','STR')
,('enchantress','Enchantress','INT')
,('huskar','Huskar','STR')
,('night_stalker','Night Stalker','STR')
,('broodmother','Broodmother','AGI')
,('bounty_hunter','Bounty Hunter','AGI')
,('weaver','Weaver','AGI')
,('jakiro','Jakiro','INT')
,('batrider','Batrider','INT')
,('chen','Chen','INT')
,('spectre','Spectre','AGI')
,('doom_bringer','Doom','STR')
,('ancient_apparition','Ancient Apparition','INT')
,('ursa','Ursa','AGI')
,('spirit_breaker','Spirit Breaker','STR')
,('gyrocopter','Gyrocopter','AGI')
,('alchemist','Alchemist','STR')
,('invoker','Invoker','INT')
,('silencer','Silencer','INT')
,('obsidian_destroyer','Outworld Devourer','INT')
,('lycan','Lycan','STR')
,('brewmaster','Brewmaster','STR')
,('shadow_demon','Shadow Demon','INT')
,('lone_druid','Lone Druid','AGI')
,('chaos_knight','Chaos Knight','STR')
,('meepo','Meepo','AGI')
,('treant','Treant Protector','STR')
,('ogre_magi','Ogre Magi','INT')
,('undying','Undying','STR')
,('rubick','Rubick','INT')
,('disruptor','Disruptor','INT')
,('nyx_assassin','Nyx Assassin','AGI')
,('naga_siren','Naga Siren','AGI')
,('keeper_of_the_light','Keeper of the Light','INT')
,('wisp','Io','STR')
,('visage','Visage','INT')
,('slark','Slark','AGI')
,('medusa','Medusa','AGI')
,('troll_warlord','Troll Warlord','AGI')
,('centaur','Centaur Warrunner','STR')
,('magnataur','Magnus','STR')
,('shredder','Timbersaw','STR')
,('bristleback','Bristleback','STR')
,('tusk','Tusk','STR')
,('skywrath_mage','Skywrath Mage','INT')
,('abaddon','Abaddon','STR')
,('elder_titan','Elder Titan','STR')
,('legion_commander','Legion Commander','STR')
,('ember_spirit','Ember Spirit','AGI')
,('earth_spirit','Earth Spirit','STR')
,('abyssal_underlord','Underlord','STR')
,('terrorblade','Terrorblade','AGI')
,('phoenix','Phoenix','STR')
,('techies','Techies','INT')
,('oracle','Oracle','INT')
,('winter_wyvern','Winter Wyvern','INT')
,('arc_warden','Arc Warden','AGI');

INSERT INTO ITEM (name) VALUES
('blink')
,('blades_of_attack')
,('broadsword')
,('chainmail')
,('claymore')
,('helm_of_iron_will')
,('javelin')
,('mithril_hammer')
,('platemail')
,('quarterstaff')
,('quelling_blade')
,('ring_of_protection')
,('stout_shield')
,('gauntlets')
,('slippers')
,('mantle')
,('branches')
,('belt_of_strength')
,('boots_of_elves')
,('robe')
,('circlet')
,('ogre_axe')
,('blade_of_alacrity')
,('staff_of_wizardry')
,('ultimate_orb')
,('gloves')
,('lifesteal')
,('ring_of_regen')
,('sobi_mask')
,('boots')
,('gem')
,('cloak')
,('talisman_of_evasion')
,('cheese')
,('magic_stick')
,('recipe_magic_wand')
,('magic_wand')
,('ghost')
,('clarity')
,('flask')
,('dust')
,('bottle')
,('ward_observer')
,('ward_sentry')
,('tango')
,('courier')
,('tpscroll')
,('recipe_travel_boots')
,('travel_boots')
,('recipe_phase_boots')
,('phase_boots')
,('demon_edge')
,('eagle')
,('reaver')
,('relic')
,('hyperstone')
,('ring_of_health')
,('void_stone')
,('mystic_staff')
,('energy_booster')
,('point_booster')
,('vitality_booster')
,('recipe_power_treads')
,('power_treads')
,('recipe_hand_of_midas')
,('hand_of_midas')
,('recipe_oblivion_staff')
,('oblivion_staff')
,('recipe_pers')
,('pers')
,('recipe_poor_mans_shield')
,('poor_mans_shield')
,('recipe_bracer')
,('bracer')
,('recipe_wraith_band')
,('wraith_band')
,('recipe_null_talisman')
,('null_talisman')
,('recipe_mekansm')
,('mekansm')
,('recipe_vladmir')
,('vladmir')
,('flying_courier')
,('recipe_buckler')
,('buckler')
,('recipe_ring_of_basilius')
,('ring_of_basilius')
,('recipe_pipe')
,('pipe')
,('recipe_urn_of_shadows')
,('urn_of_shadows')
,('recipe_headdress')
,('headdress')
,('recipe_sheepstick')
,('sheepstick')
,('recipe_orchid')
,('orchid')
,('recipe_cyclone')
,('cyclone')
,('recipe_force_staff')
,('force_staff')
,('recipe_dagon')
,('recipe_dagon_2')
,('recipe_dagon_3')
,('recipe_dagon_4')
,('recipe_dagon_5')
,('dagon')
,('dagon_2')
,('dagon_3')
,('dagon_4')
,('dagon_5')
,('recipe_necronomicon')
,('recipe_necronomicon_2')
,('recipe_necronomicon_3')
,('necronomicon')
,('necronomicon_2')
,('necronomicon_3')
,('recipe_ultimate_scepter')
,('ultimate_scepter')
,('recipe_refresher')
,('refresher')
,('recipe_assault')
,('assault')
,('recipe_heart')
,('heart')
,('recipe_black_king_bar')
,('black_king_bar')
,('aegis')
,('recipe_shivas_guard')
,('shivas_guard')
,('recipe_bloodstone')
,('bloodstone')
,('recipe_sphere')
,('sphere')
,('recipe_vanguard')
,('vanguard')
,('recipe_blade_mail')
,('blade_mail')
,('recipe_soul_booster')
,('soul_booster')
,('recipe_hood_of_defiance')
,('hood_of_defiance')
,('recipe_rapier')
,('rapier')
,('recipe_monkey_king_bar')
,('monkey_king_bar')
,('recipe_radiance')
,('radiance')
,('recipe_butterfly')
,('butterfly')
,('recipe_greater_crit')
,('greater_crit')
,('recipe_basher')
,('basher')
,('recipe_bfury')
,('bfury')
,('recipe_manta')
,('manta')
,('recipe_lesser_crit')
,('lesser_crit')
,('recipe_armlet')
,('armlet')
,('recipe_invis_sword')
,('invis_sword')
,('recipe_sange_and_yasha')
,('sange_and_yasha')
,('recipe_satanic')
,('satanic')
,('recipe_mjollnir')
,('mjollnir')
,('recipe_skadi')
,('skadi')
,('recipe_sange')
,('sange')
,('recipe_helm_of_the_dominator')
,('helm_of_the_dominator')
,('recipe_maelstrom')
,('maelstrom')
,('recipe_desolator')
,('desolator')
,('recipe_yasha')
,('yasha')
,('recipe_mask_of_madness')
,('mask_of_madness')
,('recipe_diffusal_blade')
,('recipe_diffusal_blade_')
,('diffusal_blade')
,('diffusal_blade_')
,('recipe_ethereal_blade')
,('ethereal_blade')
,('recipe_soul_ring')
,('soul_ring')
,('recipe_arcane_boots')
,('arcane_boots')
,('orb_of_venom')
,('recipe_ancient_janggo')
,('ancient_janggo')
,('recipe_medallion_of_courage')
,('medallion_of_courage')
,('smoke_of_deceit')
,('recipe_veil_of_discord')
,('veil_of_discord')
,('recipe_rod_of_atos')
,('rod_of_atos')
,('recipe_abyssal_blade')
,('abyssal_blade')
,('recipe_heavens_halberd')
,('heavens_halberd')
,('recipe_ring_of_aquila')
,('ring_of_aquila')
,('recipe_tranquil_boots')
,('tranquil_boots')
,('shadow_amulet')
,('enchanted_mango')
,('ward_dispenser')
,('travel_boots_')
,('lotus_orb')
,('solar_crest')
,('guardian_greaves')
,('octarine_core')
,('moon_shard')
,('silver_edge')
,('glimmer_cape')
,('halloween_candy_corn')
,('mystery_hook')
,('mystery_arrow')
,('mystery_missile')
,('mystery_toss')
,('mystery_vacuum')
,('halloween_rapier')
,('greevil_whistle')
,('greevil_whistle_toggle')
,('present')
,('winter_stocking')
,('winter_skates')
,('winter_cake')
,('winter_cookie')
,('winter_coco')
,('winter_ham')
,('winter_kringle')
,('winter_mushroom')
,('winter_greevil_treat')
,('winter_greevil_garbage')
,('winter_greevil_chewy')
,('tango_single')
,('crimson_guard')
,('recipe_iron_talon')
,('iron_talon')
,('recipe_aether_lens')
,('aether_lens')
,('recipe_dragon_lance')
,('dragon_lance')
,('faerie_fire')
,('wind_lace')
,('recipe_bloodthorn')
,('bloodthorn')
,('recipe_echo_sabre')
,('echo_sabre')
,('tome_of_knowledge')
,('recipe_hurricane_pike')
,('hurricane_pike')
,('blight_stone')
,('infused_raindrop');