INSERT INTO HERO (name, localized_name, primary_attribute) VALUES
 ('antimage','Anti-Mage','AGI')
,('axe','Axe','STR')
,('bane','Bane','INT')
,('bloodseeker','Bloodseeker','AGI')
,('crystal_maiden','Crystal Maiden','INT')
,('drow_ranger','Drow Ranger','AGI')
,('earthshaker','Earthshaker','STR')
,('juggernaut','Juggernaut','AGI')
,('mirana','Mirana','AGI')
,('nevermore','Shadow Fiend','AGI')
,('morphling','Morphling','AGI')
,('phantom_lancer','Phantom Lancer','AGI')
,('puck','Puck','INT')
,('pudge','Pudge','STR')
,('razor','Razor','AGI')
,('sand_king','Sand King','STR')
,('storm_spirit','Storm Spirit','INT')
,('sven','Sven','STR')
,('tiny','Tiny','STR')
,('vengefulspirit','Vengeful Spirit','AGI')
,('windrunner','Windranger','INT')
,('zuus','Zeus','INT')
,('kunkka','Kunkka','STR')
,('lina','Lina','INT')
,('lich','Lich','INT')
,('lion','Lion','INT')
,('shadow_shaman','Shadow Shaman','INT')
,('slardar','Slardar','STR')
,('tidehunter','Tidehunter','STR')
,('witch_doctor','Witch Doctor','INT')
,('riki','Riki','AGI')
,('enigma','Enigma','INT')
,('tinker','Tinker','INT')
,('sniper','Sniper','AGI')
,('necrolyte','Necrophos','INT')
,('warlock','Warlock','INT')
,('beastmaster','Beastmaster','STR')
,('queenofpain','Queen of Pain','INT')
,('venomancer','Venomancer','AGI')
,('faceless_void','Faceless Void','AGI')
,('skeleton_king','Wraith King','STR')
,('death_prophet','Death Prophet','INT')
,('phantom_assassin','Phantom Assassin','AGI')
,('pugna','Pugna','INT')
,('templar_assassin','Templar Assassin','AGI')
,('viper','Viper','AGI')
,('luna','Luna','AGI')
,('dragon_knight','Dragon Knight','STR')
,('dazzle','Dazzle','INT')
,('rattletrap','Clockwerk','STR')
,('leshrac','Leshrac','INT')
,('furion','Nature''s Prophet','INT')
,('life_stealer','Lifestealer','STR')
,('dark_seer','Dark Seer','INT')
,('clinkz','Clinkz','AGI')
,('omniknight','Omniknight','STR')
,('enchantress','Enchantress','INT')
,('huskar','Huskar','STR')
,('night_stalker','Night Stalker','STR')
,('broodmother','Broodmother','AGI')
,('bounty_hunter','Bounty Hunter','AGI')
,('weaver','Weaver','AGI')
,('jakiro','Jakiro','INT')
,('batrider','Batrider','INT')
,('chen','Chen','INT')
,('spectre','Spectre','AGI')
,('doom_bringer','Doom','STR')
,('ancient_apparition','Ancient Apparition','INT')
,('ursa','Ursa','AGI')
,('spirit_breaker','Spirit Breaker','STR')
,('gyrocopter','Gyrocopter','AGI')
,('alchemist','Alchemist','STR')
,('invoker','Invoker','INT')
,('silencer','Silencer','INT')
,('obsidian_destroyer','Outworld Devourer','INT')
,('lycan','Lycan','STR')
,('brewmaster','Brewmaster','STR')
,('shadow_demon','Shadow Demon','INT')
,('lone_druid','Lone Druid','AGI')
,('chaos_knight','Chaos Knight','STR')
,('meepo','Meepo','AGI')
,('treant','Treant Protector','STR')
,('ogre_magi','Ogre Magi','INT')
,('undying','Undying','STR')
,('rubick','Rubick','INT')
,('disruptor','Disruptor','INT')
,('nyx_assassin','Nyx Assassin','AGI')
,('naga_siren','Naga Siren','AGI')
,('keeper_of_the_light','Keeper of the Light','INT')
,('wisp','Io','STR')
,('visage','Visage','INT')
,('slark','Slark','AGI')
,('medusa','Medusa','AGI')
,('troll_warlord','Troll Warlord','AGI')
,('centaur','Centaur Warrunner','STR')
,('magnataur','Magnus','STR')
,('shredder','Timbersaw','STR')
,('bristleback','Bristleback','STR')
,('tusk','Tusk','STR')
,('skywrath_mage','Skywrath Mage','INT')
,('abaddon','Abaddon','STR')
,('elder_titan','Elder Titan','STR')
,('legion_commander','Legion Commander','STR')
,('ember_spirit','Ember Spirit','AGI')
,('earth_spirit','Earth Spirit','STR')
,('abyssal_underlord','Underlord','STR')
,('terrorblade','Terrorblade','AGI')
,('phoenix','Phoenix','STR')
,('techies','Techies','INT')
,('oracle','Oracle','INT')
,('winter_wyvern','Winter Wyvern','INT')
,('arc_warden','Arc Warden','AGI');